### ISSUE TITLE
BlurRelax installation

### ISSUE THREAD

**Issue by Ndoye80** [blurstudio/blurRelax#8]
Hi, i would appreciate a little guide on how to install it. Thank you sir

**Comment by tbttfox** [comment]
Sure.
From the main page for this repo, there's a link for Releases (Near the top, there's commits, branches, releases, contributors, and the License (MIT in this case))
Click on Release, then download BlurRelax.zip.
I've compiled for maya 2016.5, 2017, and 2018. So find the .mll file in the folder corresponding to your installed version of maya in the zip file.
Then put that mll into your maya user plugins folder.  On Windows, it's usually in 
`C:\Users\<yourUsername>\Documents\maya\<mayaVersion>\plug-ins`
If that folder doesn't exist, create it.
Then just drop the .mll file in there, and start Maya.

To create the deformer, just run `cmds.deformer(type='BlurRelax')` in python with your object selected.

**Comment by Ndoye80** [comment]
Thank you very much it works 👍

**Comment by tbttfox** [comment]
If you wouldn't mind, please close the issue.
